# Projeto Redes Neurais — Experimentos com Modelos

Este notebook consolida a execução final dos experimentos com modelos do projeto. O fluxo foi organizado para carregar o artefato `datasets.pkl`, rodar os modelos tabulares e baseados em imagem com dados originais e enriquecidos, registrar métricas padronizadas por execução e salvar um CSV único ao final.

A estrutura segue a mesma ideia de organização adotada em `project_data.ipynb`: abertura, infraestrutura compartilhada, definições de modelos, execução dos experimentos e consolidação final.

In [7]:
import pickle
import time
from pathlib import Path

import mlx.core as mx
import mlx.nn as mnn
import mlx.optimizers as optim
import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score, classification_report, f1_score, precision_score, recall_score
from tqdm.auto import tqdm
from xgboost import XGBClassifier

RANDOM_STATE = 42
BATCH_SIZE = 64
EPOCHS = 30
LEARNING_RATE = 0.0008
DATASETS_PICKLE_PATH = Path("data/datasets.pkl")
RESULTS_CSV_PATH = Path("data/results_models.csv")
RESULT_KEY_COLUMNS = ["model_name", "dataset_name", "input_type", "used_enriched_data"]
RESULT_COLUMNS = [
    "model_name",
    "dataset_name",
    "input_type",
    "used_enriched_data",
    "train_samples",
    "test_samples",
    "num_classes",
    "metric_average",
    "accuracy",
    "f1",
    "precision",
    "recall",
    "training_time_sec",
    "epochs",
    "image_height",
    "image_width",
]
REQUIRED_DATASET_KEYS = {
    "X_train",
    "X_test",
    "X_train_enriched",
    "y_train_enriched",
    "y_train",
    "y_test",
    "X_train_images",
    "X_train_images_enriched",
    "X_test_images",
}

## Infraestrutura compartilhada

As células abaixo carregam o artefato consolidado de dados e definem funções utilitárias reaproveitadas por todos os experimentos do notebook.

In [8]:
with open(DATASETS_PICKLE_PATH, "rb") as f:
    datasets = pickle.load(f)

for dataset_name, dataset_bundle in datasets.items():
    missing_keys = REQUIRED_DATASET_KEYS.difference(dataset_bundle.keys())
    if missing_keys:
        raise KeyError(
            f"O dataset '{dataset_name}' está sem as chaves esperadas: {sorted(missing_keys)}"
        )

print(f"datasets carregado de: {DATASETS_PICKLE_PATH}")
print("chaves disponíveis:", list(datasets.keys()))

resumo_datasets = []
for dataset_name, dataset_bundle in datasets.items():
    resumo_datasets.append(
        {
            "dataset_name": dataset_name,
            "X_train_shape": dataset_bundle["X_train"].shape,
            "X_train_enriched_shape": dataset_bundle["X_train_enriched"].shape,
            "X_test_shape": dataset_bundle["X_test"].shape,
            "X_train_images_shape": dataset_bundle["X_train_images"].shape,
            "X_train_images_enriched_shape": dataset_bundle["X_train_images_enriched"].shape,
            "X_test_images_shape": dataset_bundle["X_test_images"].shape,
        }
    )

pd.DataFrame(resumo_datasets)

datasets carregado de: data/datasets.pkl
chaves disponíveis: ['adult income', 'student', 'statlog', 'maintenance', 'stroke']

,dataset_name,X_train_shape,X_train_enriched_shape,X_test_shape,X_train_images_shape,X_train_images_enriched_shape,X_test_images_shape
0,adult income,"(39073, 12)","(59448, 12)","(9769, 12)","(39073, 24, 24)","(59448, 24, 24)","(9769, 24, 24)"
1,student,"(3539, 36)","(5301, 36)","(885, 36)","(3539, 72, 72)","(5301, 72, 72)","(885, 72, 72)"
2,statlog,"(46400, 7)","(255283, 7)","(11600, 7)","(46400, 14, 14)","(255283, 14, 14)","(11600, 14, 14)"
3,maintenance,"(8000, 6)","(15458, 6)","(2000, 6)","(8000, 12, 12)","(15458, 12, 12)","(2000, 12, 12)"
4,stroke,"(4088, 10)","(7778, 10)","(1022, 10)","(4088, 20, 20)","(7778, 20, 20)","(1022, 20, 20)"

In [9]:
def target_to_numpy(target):
    if isinstance(target, pd.Series):
        return target.to_numpy()
    return np.asarray(target)


def normalize_bool(value):
    if isinstance(value, str):
        return value.strip().lower() in {"true", "1", "yes"}
    if pd.isna(value):
        return False
    return bool(value)


def build_label_mapping(*targets):
    unique_values = set()
    for target in targets:
        unique_values.update(target_to_numpy(target).tolist())
    ordered_values = sorted(unique_values)
    return {value: index for index, value in enumerate(ordered_values)}


def encode_target(target, label_mapping):
    target_array = target_to_numpy(target)
    return np.array([label_mapping[value] for value in target_array.tolist()], dtype=np.int32)


def convert_images_to_channels_last(images):
    images_array = np.asarray(images, dtype=np.float32)
    return np.expand_dims(images_array, axis=-1) / 255.0


def compute_metrics(y_true, y_pred):
    num_classes = len(np.unique(y_true))
    average = "binary" if num_classes == 2 else "macro"

    return {
        "accuracy": accuracy_score(y_true, y_pred),
        "f1": f1_score(y_true, y_pred, average=average, zero_division=0),
        "precision": precision_score(y_true, y_pred, average=average, zero_division=0),
        "recall": recall_score(y_true, y_pred, average=average, zero_division=0),
        "metric_average": average,
        "num_classes": num_classes,
    }


def build_experiment_key(model_name, dataset_name, input_type, used_enriched_data):
    return (
        str(model_name),
        str(dataset_name),
        str(input_type),
        normalize_bool(used_enriched_data),
    )


def standardize_results_df(results_df):
    standardized_df = results_df.copy()
    for column in RESULT_COLUMNS:
        if column not in standardized_df.columns:
            standardized_df[column] = pd.NA

    if not standardized_df.empty and "used_enriched_data" in standardized_df.columns:
        standardized_df["used_enriched_data"] = standardized_df["used_enriched_data"].map(normalize_bool)

    return standardized_df[RESULT_COLUMNS]


def load_results_csv(results_csv_path):
    if not results_csv_path.exists() or results_csv_path.stat().st_size == 0:
        return pd.DataFrame(columns=RESULT_COLUMNS)

    results_df = pd.read_csv(results_csv_path)
    return standardize_results_df(results_df)


def initialize_results_csv(results_csv_path):
    results_df = load_results_csv(results_csv_path)
    results_csv_path.parent.mkdir(parents=True, exist_ok=True)
    results_df.to_csv(results_csv_path, index=False)
    return results_df


def build_completed_experiment_keys(results_df):
    if results_df.empty:
        return set()

    missing_columns = [column for column in RESULT_KEY_COLUMNS if column not in results_df.columns]
    if missing_columns:
        raise KeyError(
            f"O CSV de resultados está sem as colunas de chave esperadas: {missing_columns}"
        )

    completed_keys = set()
    for _, row in results_df.iterrows():
        completed_keys.add(
            build_experiment_key(
                row["model_name"],
                row["dataset_name"],
                row["input_type"],
                row["used_enriched_data"],
            )
        )

    return completed_keys


def experiment_exists(
    completed_experiment_keys,
    *,
    model_name,
    dataset_name,
    input_type,
    used_enriched_data,
):
    experiment_key = build_experiment_key(
        model_name,
        dataset_name,
        input_type,
        used_enriched_data,
    )
    return experiment_key in completed_experiment_keys


def print_skip_message(model_name, dataset_name, input_type, used_enriched_data):
    origem = "enriched" if normalize_bool(used_enriched_data) else "original"
    print(
        f"Pulando experimento já concluído: modelo={model_name} | dataset={dataset_name} | "
        f"entrada={input_type} | dados={origem}"
    )


def register_result(
    results,
    completed_experiment_keys,
    results_csv_path,
    *,
    model_name,
    dataset_name,
    input_type,
    used_enriched_data,
    train_samples,
    test_samples,
    training_time_sec,
    metrics,
    extra=None,
):
    row = {column: None for column in RESULT_COLUMNS}
    row.update(
        {
            "model_name": model_name,
            "dataset_name": dataset_name,
            "input_type": input_type,
            "used_enriched_data": normalize_bool(used_enriched_data),
            "train_samples": train_samples,
            "test_samples": test_samples,
            "num_classes": metrics["num_classes"],
            "metric_average": metrics["metric_average"],
            "accuracy": metrics["accuracy"],
            "f1": metrics["f1"],
            "precision": metrics["precision"],
            "recall": metrics["recall"],
            "training_time_sec": training_time_sec,
        }
    )

    if extra:
        for key, value in extra.items():
            if key in row:
                row[key] = value

    experiment_key = build_experiment_key(
        row["model_name"],
        row["dataset_name"],
        row["input_type"],
        row["used_enriched_data"],
    )
    if experiment_key in completed_experiment_keys:
        print_skip_message(
            row["model_name"],
            row["dataset_name"],
            row["input_type"],
            row["used_enriched_data"],
        )
        return False

    row_df = pd.DataFrame([row], columns=RESULT_COLUMNS)
    results_csv_path.parent.mkdir(parents=True, exist_ok=True)
    write_header = not results_csv_path.exists() or results_csv_path.stat().st_size == 0
    row_df.to_csv(results_csv_path, mode="a", header=write_header, index=False)

    results.append(row)
    completed_experiment_keys.add(experiment_key)
    return True


def print_experiment_summary(model_name, dataset_name, input_type, used_enriched_data, metrics, training_time_sec):
    origem = "enriched" if normalize_bool(used_enriched_data) else "original"
    print("-" * 80)
    print(
        f"Modelo: {model_name} | Dataset: {dataset_name} | Entrada: {input_type} | Dados: {origem}"
    )
    print(f"Accuracy: {metrics['accuracy']:.4f}")
    print(f"F1: {metrics['f1']:.4f}")
    print(f"Precision: {metrics['precision']:.4f}")
    print(f"Recall: {metrics['recall']:.4f}")
    print(f"Tempo de treinamento: {training_time_sec:.2f}s")

## Definições de modelos

A arquitetura base da CNN e as configurações dos modelos ficam centralizadas aqui para evitar repetição nas células de execução.

In [10]:
def estimate_conv_output_size(size, stride):
    return int(np.ceil(size / stride))


def compute_pooling_targets(image_height, image_width):
    base_targets = [(15, 15), (7, 7), (3, 3), (1, 1)]
    strides = [1, 2, 2, 2]

    current_height = int(image_height)
    current_width = int(image_width)
    if current_height < 1 or current_width < 1:
        raise ValueError(
            f"Tamanho de imagem inválido para a CNN: {(image_height, image_width)}"
        )

    pooling_targets = []
    for (base_height, base_width), stride in zip(base_targets, strides):
        conv_height = estimate_conv_output_size(current_height, stride)
        conv_width = estimate_conv_output_size(current_width, stride)

        target_height = max(1, min(base_height, conv_height))
        target_width = max(1, min(base_width, conv_width))

        if target_height > conv_height or target_width > conv_width:
            raise ValueError(
                "Pooling target inválido calculado para a CNN: "
                f"entrada={(current_height, current_width)}, conv={(conv_height, conv_width)}, "
                f"target={(target_height, target_width)}"
            )

        pooling_targets.append((target_height, target_width))
        current_height, current_width = target_height, target_width

    return pooling_targets


def adaptive_max_pool2d(x, output_size):
    in_height, in_width = int(x.shape[1]), int(x.shape[2])
    out_height = min(int(output_size[0]), in_height)
    out_width = min(int(output_size[1]), in_width)

    if out_height < 1 or out_width < 1:
        raise ValueError(
            f"Adaptive pooling recebeu target inválido {output_size} para entrada {(in_height, in_width)}"
        )

    stride_height = max(1, in_height // out_height)
    stride_width = max(1, in_width // out_width)
    kernel_height = max(1, in_height - (out_height - 1) * stride_height)
    kernel_width = max(1, in_width - (out_width - 1) * stride_width)

    pool = mnn.MaxPool2d(
        kernel_size=(kernel_height, kernel_width),
        stride=(stride_height, stride_width),
        padding=0,
    )
    return pool(x)


class SEBlock(mnn.Module):
    def __init__(self, channels, reduction=16):
        super().__init__()
        hidden = max(1, channels // reduction)
        self.fc1 = mnn.Linear(channels, hidden)
        self.fc2 = mnn.Linear(hidden, channels)

    def __call__(self, x):
        weights = mx.mean(x, axis=(1, 2))
        weights = mnn.relu(self.fc1(weights))
        weights = mx.sigmoid(self.fc2(weights))
        weights = mx.reshape(weights, (x.shape[0], 1, 1, x.shape[-1]))
        return x * weights


class ConvBlock(mnn.Module):
    def __init__(
        self,
        in_channels,
        out_channels,
        stride,
        target_size,
        use_se=False,
        use_asymmetric=False,
        use_dilation=False,
        use_residual=False,
    ):
        super().__init__()
        self.target_size = target_size
        self.use_se = use_se
        self.use_asymmetric = use_asymmetric
        self.use_residual = use_residual

        dilation = 2 if use_dilation else 1
        padding = dilation

        if use_asymmetric:
            self.conv_a = mnn.Conv2d(
                in_channels,
                out_channels,
                kernel_size=(1, 3),
                stride=(1, stride),
                padding=(0, padding),
                dilation=(1, dilation),
            )
            self.conv_b = mnn.Conv2d(
                out_channels,
                out_channels,
                kernel_size=(3, 1),
                stride=(stride, 1),
                padding=(padding, 0),
                dilation=(dilation, 1),
            )
        else:
            self.conv = mnn.Conv2d(
                in_channels,
                out_channels,
                kernel_size=3,
                stride=stride,
                padding=padding,
                dilation=dilation,
            )

        self.bn = mnn.BatchNorm(out_channels)
        self.se = SEBlock(out_channels) if use_se else None

        needs_projection = use_residual and (in_channels != out_channels or stride != 1)
        self.proj = (
            mnn.Conv2d(in_channels, out_channels, kernel_size=1, stride=stride)
            if needs_projection
            else None
        )

    def __call__(self, x):
        shortcut = x

        if self.use_asymmetric:
            x = self.conv_a(x)
            x = mnn.relu(x)
            x = self.conv_b(x)
        else:
            x = self.conv(x)

        x = self.bn(x)
        x = mnn.relu(x)

        if self.se is not None:
            x = self.se(x)

        if self.use_residual:
            if self.proj is not None:
                shortcut = self.proj(shortcut)
            x = x + shortcut

        x = adaptive_max_pool2d(x, self.target_size)
        return x


class NCTD_CNN_Base(mnn.Module):
    def __init__(
        self,
        num_classes,
        input_shape=None,
        use_se=False,
        use_asymmetric=False,
        use_dilation=False,
        use_residual=False,
    ):
        super().__init__()

        if input_shape is None:
            pooling_targets = [(15, 15), (7, 7), (3, 3), (1, 1)]
        else:
            if len(input_shape) != 2:
                raise ValueError(f"input_shape inválido para a CNN: {input_shape}")
            pooling_targets = compute_pooling_targets(input_shape[0], input_shape[1])

        self.pooling_targets = pooling_targets

        self.block0 = ConvBlock(
            1,
            64,
            stride=1,
            target_size=pooling_targets[0],
            use_se=use_se,
            use_asymmetric=use_asymmetric,
            use_dilation=False,
            use_residual=use_residual,
        )
        self.block1 = ConvBlock(
            64,
            64,
            stride=2,
            target_size=pooling_targets[1],
            use_se=use_se,
            use_asymmetric=use_asymmetric,
            use_dilation=use_dilation,
            use_residual=use_residual,
        )
        self.block2 = ConvBlock(
            64,
            64,
            stride=2,
            target_size=pooling_targets[2],
            use_se=use_se,
            use_asymmetric=use_asymmetric,
            use_dilation=use_dilation,
            use_residual=use_residual,
        )
        self.block3 = ConvBlock(
            64,
            64,
            stride=2,
            target_size=pooling_targets[3],
            use_se=use_se,
            use_asymmetric=use_asymmetric,
            use_dilation=False,
            use_residual=use_residual,
        )

        self.fc = mnn.Linear(64, 32)
        self.out = mnn.Linear(32, num_classes)

    def __call__(self, x):
        x = self.block0(x)
        x = self.block1(x)
        x = self.block2(x)
        x = self.block3(x)
        x = mx.mean(x, axis=(1, 2))
        x = mnn.relu(self.fc(x))
        x = self.out(x)
        return x


CNN_MODEL_BUILDERS = [
    (
        "NCTD Base",
        lambda num_classes, input_shape: NCTD_CNN_Base(
            num_classes=num_classes,
            input_shape=input_shape,
        ),
    ),
    (
        "NCTD Attention (SE)",
        lambda num_classes, input_shape: NCTD_CNN_Base(
            num_classes=num_classes,
            input_shape=input_shape,
            use_se=True,
        ),
    ),
    (
        "NCTD Asymmetric Kernels",
        lambda num_classes, input_shape: NCTD_CNN_Base(
            num_classes=num_classes,
            input_shape=input_shape,
            use_asymmetric=True,
        ),
    ),
    (
        "NCTD Dilated Convolutions",
        lambda num_classes, input_shape: NCTD_CNN_Base(
            num_classes=num_classes,
            input_shape=input_shape,
            use_dilation=True,
        ),
    ),
    (
        "NCTD Residual",
        lambda num_classes, input_shape: NCTD_CNN_Base(
            num_classes=num_classes,
            input_shape=input_shape,
            use_residual=True,
        ),
    ),
]

## Funções de execução dos experimentos

As rotinas abaixo recebem explicitamente treino e teste de cada dataset, executam o modelo correspondente e registram os resultados em uma estrutura única.

In [11]:
def run_xgboost_experiment(
    *,
    dataset_name,
    X_train,
    y_train,
    X_test,
    y_test,
    used_enriched_data,
    results,
    completed_experiment_keys,
    results_csv_path,
):
    label_mapping = build_label_mapping(y_train, y_test)
    y_train_encoded = encode_target(y_train, label_mapping)
    y_test_encoded = encode_target(y_test, label_mapping)
    num_classes = len(label_mapping)

    model_params = {
        "n_estimators": 100,
        "learning_rate": 0.1,
        "max_depth": 6,
        "random_state": RANDOM_STATE,
    }

    if num_classes == 2:
        model_params.update({"objective": "binary:logistic", "eval_metric": "logloss"})
    else:
        model_params.update(
            {
                "objective": "multi:softprob",
                "num_class": num_classes,
                "eval_metric": "mlogloss",
            }
        )

    model = XGBClassifier(**model_params)

    start_time = time.perf_counter()
    model.fit(X_train, y_train_encoded)
    training_time_sec = time.perf_counter() - start_time

    y_pred = model.predict(X_test)
    metrics = compute_metrics(y_test_encoded, y_pred)

    print_experiment_summary(
        "XGBoost",
        dataset_name,
        "tabular",
        used_enriched_data,
        metrics,
        training_time_sec,
    )
    print(classification_report(y_test_encoded, y_pred, zero_division=0))

    return register_result(
        results,
        completed_experiment_keys,
        results_csv_path,
        model_name="XGBoost",
        dataset_name=dataset_name,
        input_type="tabular",
        used_enriched_data=used_enriched_data,
        train_samples=len(X_train),
        test_samples=len(X_test),
        training_time_sec=training_time_sec,
        metrics=metrics,
    )


def run_cnn_experiment(
    *,
    model_name,
    model_builder,
    dataset_name,
    X_train_images,
    y_train,
    X_test_images,
    y_test,
    used_enriched_data,
    results,
    completed_experiment_keys,
    results_csv_path,
    epochs=EPOCHS,
):
    train_images_array = np.asarray(X_train_images)
    test_images_array = np.asarray(X_test_images)

    if train_images_array.ndim != 3 or test_images_array.ndim != 3:
        raise ValueError(
            f"As imagens da CNN devem ter shape (N, H, W). "
            f"Recebido treino={train_images_array.shape} e teste={test_images_array.shape} "
            f"para o dataset '{dataset_name}'."
        )

    input_shape = tuple(train_images_array.shape[1:3])
    if tuple(test_images_array.shape[1:3]) != input_shape:
        raise ValueError(
            f"Shapes de imagem incompatíveis entre treino e teste para o dataset '{dataset_name}': "
            f"treino={input_shape}, teste={tuple(test_images_array.shape[1:3])}"
        )

    pooling_targets = compute_pooling_targets(*input_shape)

    label_mapping = build_label_mapping(y_train, y_test)
    y_train_encoded = encode_target(y_train, label_mapping)
    y_test_encoded = encode_target(y_test, label_mapping)
    num_classes = len(label_mapping)
    if num_classes < 2:
        raise ValueError(
            f"A CNN exige pelo menos 2 classes. Dataset '{dataset_name}' retornou {num_classes}."
        )

    X_train_mlx = convert_images_to_channels_last(train_images_array)
    X_test_mlx = convert_images_to_channels_last(test_images_array)

    model = model_builder(num_classes, input_shape)
    mx.eval(model.parameters())
    optimizer = optim.Adam(learning_rate=LEARNING_RATE)

    def loss_fn(model, x, y):
        logits = model(x)
        return mx.mean(mnn.losses.cross_entropy(logits, y))

    loss_and_grad_fn = mnn.value_and_grad(model, loss_fn)
    rng = np.random.default_rng(RANDOM_STATE)

    num_batches_train = (len(X_train_mlx) + BATCH_SIZE - 1) // BATCH_SIZE
    num_batches_test = (len(X_test_mlx) + BATCH_SIZE - 1) // BATCH_SIZE
    total_steps = epochs * num_batches_train + num_batches_test
    origem = "enriched" if used_enriched_data else "original"

    print(f"Pooling targets para {dataset_name}/{model_name}: {pooling_targets}")
    print(f"Número de classes na saída: {num_classes}")

    start_time = time.perf_counter()

    with tqdm(
        total=total_steps,
        desc=f"{dataset_name} | {model_name} | {origem}",
        unit="batch",
    ) as pbar:
        for epoch in range(epochs):
            model.train()
            running_loss = 0.0
            permutation = rng.permutation(len(X_train_mlx))

            for start in range(0, len(X_train_mlx), BATCH_SIZE):
                end = min(start + BATCH_SIZE, len(X_train_mlx))
                batch_indices = permutation[start:end]

                batch_x = mx.array(X_train_mlx[batch_indices])
                batch_y = mx.array(y_train_encoded[batch_indices])

                loss, grads = loss_and_grad_fn(model, batch_x, batch_y)
                optimizer.update(model, grads)
                mx.eval(model.parameters(), optimizer.state)

                loss_value = loss.item()
                running_loss += loss_value * len(batch_indices)

                pbar.update(1)
                pbar.set_postfix(
                    {
                        "epoch": f"{epoch + 1}/{epochs}",
                        "loss": f"{loss_value:.4f}",
                    }
                )

            epoch_loss = running_loss / len(X_train_mlx)
            pbar.set_postfix(
                {
                    "epoch": f"{epoch + 1}/{epochs}",
                    "loss": f"{epoch_loss:.4f}",
                }
            )

        model.eval()
        predictions = []

        for start in range(0, len(X_test_mlx), BATCH_SIZE):
            end = min(start + BATCH_SIZE, len(X_test_mlx))
            batch_x = mx.array(X_test_mlx[start:end])

            logits = model(batch_x)
            preds = mx.argmax(logits, axis=1)
            mx.eval(preds)

            predictions.extend(np.array(preds).tolist())
            pbar.update(1)
            pbar.set_postfix({"fase": "teste"})

    training_time_sec = time.perf_counter() - start_time
    predictions = np.array(predictions, dtype=np.int32)
    metrics = compute_metrics(y_test_encoded, predictions)

    print_experiment_summary(
        model_name,
        dataset_name,
        "image",
        used_enriched_data,
        metrics,
        training_time_sec,
    )
    print(classification_report(y_test_encoded, predictions, zero_division=0))

    return register_result(
        results,
        completed_experiment_keys,
        results_csv_path,
        model_name=model_name,
        dataset_name=dataset_name,
        input_type="image",
        used_enriched_data=used_enriched_data,
        train_samples=len(X_train_mlx),
        test_samples=len(X_test_mlx),
        training_time_sec=training_time_sec,
        metrics=metrics,
        extra={
            "epochs": epochs,
            "image_height": input_shape[0],
            "image_width": input_shape[1],
        },
    )

## Execução dos experimentos

Cada dataset é processado com o mesmo protocolo: XGBoost para dados tabulares e as variantes finais da NCTD para dados em imagem, sempre comparando treino original e treino enriquecido contra o mesmo conjunto de teste.

In [12]:
existing_results_df = initialize_results_csv(RESULTS_CSV_PATH)
completed_experiment_keys = build_completed_experiment_keys(existing_results_df)

results = []
executed_in_session = 0
skipped_in_session = 0

print(f"Resultados já persistidos no CSV: {len(completed_experiment_keys)}")

for dataset_name, dataset_bundle in datasets.items():
    print("\n" + "=" * 80)
    print(f"Iniciando experimentos para o dataset: {dataset_name}")
    print("=" * 80)

    if experiment_exists(
        completed_experiment_keys,
        model_name="XGBoost",
        dataset_name=dataset_name,
        input_type="tabular",
        used_enriched_data=False,
    ):
        skipped_in_session += 1
        print_skip_message("XGBoost", dataset_name, "tabular", False)
    else:
        executed_in_session += int(
            run_xgboost_experiment(
                dataset_name=dataset_name,
                X_train=dataset_bundle["X_train"],
                y_train=dataset_bundle["y_train"],
                X_test=dataset_bundle["X_test"],
                y_test=dataset_bundle["y_test"],
                used_enriched_data=False,
                results=results,
                completed_experiment_keys=completed_experiment_keys,
                results_csv_path=RESULTS_CSV_PATH,
            )
        )

    if experiment_exists(
        completed_experiment_keys,
        model_name="XGBoost",
        dataset_name=dataset_name,
        input_type="tabular",
        used_enriched_data=True,
    ):
        skipped_in_session += 1
        print_skip_message("XGBoost", dataset_name, "tabular", True)
    else:
        executed_in_session += int(
            run_xgboost_experiment(
                dataset_name=dataset_name,
                X_train=dataset_bundle["X_train_enriched"],
                y_train=dataset_bundle["y_train_enriched"],
                X_test=dataset_bundle["X_test"],
                y_test=dataset_bundle["y_test"],
                used_enriched_data=True,
                results=results,
                completed_experiment_keys=completed_experiment_keys,
                results_csv_path=RESULTS_CSV_PATH,
            )
        )

    for model_name, model_builder in CNN_MODEL_BUILDERS:
        if experiment_exists(
            completed_experiment_keys,
            model_name=model_name,
            dataset_name=dataset_name,
            input_type="image",
            used_enriched_data=False,
        ):
            skipped_in_session += 1
            print_skip_message(model_name, dataset_name, "image", False)
        else:
            executed_in_session += int(
                run_cnn_experiment(
                    model_name=model_name,
                    model_builder=model_builder,
                    dataset_name=dataset_name,
                    X_train_images=dataset_bundle["X_train_images"],
                    y_train=dataset_bundle["y_train"],
                    X_test_images=dataset_bundle["X_test_images"],
                    y_test=dataset_bundle["y_test"],
                    used_enriched_data=False,
                    results=results,
                    completed_experiment_keys=completed_experiment_keys,
                    results_csv_path=RESULTS_CSV_PATH,
                )
            )

        if experiment_exists(
            completed_experiment_keys,
            model_name=model_name,
            dataset_name=dataset_name,
            input_type="image",
            used_enriched_data=True,
        ):
            skipped_in_session += 1
            print_skip_message(model_name, dataset_name, "image", True)
        else:
            executed_in_session += int(
                run_cnn_experiment(
                    model_name=model_name,
                    model_builder=model_builder,
                    dataset_name=dataset_name,
                    X_train_images=dataset_bundle["X_train_images_enriched"],
                    y_train=dataset_bundle["y_train_enriched"],
                    X_test_images=dataset_bundle["X_test_images"],
                    y_test=dataset_bundle["y_test"],
                    used_enriched_data=True,
                    results=results,
                    completed_experiment_keys=completed_experiment_keys,
                    results_csv_path=RESULTS_CSV_PATH,
                )
            )

results_df = load_results_csv(RESULTS_CSV_PATH)
print(f"Experimentos executados nesta sessão: {executed_in_session}")
print(f"Experimentos pulados por já existirem: {skipped_in_session}")
print(f"Total persistido no CSV: {len(results_df)}")
results_df.head()

Resultados já persistidos no CSV: 0

================================================================================
Iniciando experimentos para o dataset: adult income
================================================================================
--------------------------------------------------------------------------------
Modelo: XGBoost | Dataset: adult income | Entrada: tabular | Dados: original
Accuracy: 0.8772
F1: 0.7167
Precision: 0.7998
Recall: 0.6493
Tempo de treinamento: 0.22s
              precision    recall  f1-score   support

           0       0.90      0.95      0.92      7431
           1       0.80      0.65      0.72      2338

    accuracy                           0.88      9769
   macro avg       0.85      0.80      0.82      9769
weighted avg       0.87      0.88      0.87      9769

--------------------------------------------------------------------------------
Modelo: XGBoost | Dataset: adult income | Entrada: tabular | Dados: enriched
Accuracy: 0.8747
F1: 0.7083
Precision: 0.7998
Recall: 0.6356
Tempo de treinamento: 0.19s
              precision    recall  f1-score   support

           0       0.89      0.95      0.92      7431
           1       0.80      0.64      0.71      2338

    accuracy                           0.87      9769
   macro avg       0.85      0.79      0.81      9769
weighted avg       0.87      0.87      0.87      9769

Pooling targets para adult income/NCTD Base: [(15, 15), (7, 7), (3, 3), (1, 1)]
Número de classes na saída: 2

adult income | NCTD Base | original: 100%|██████████| 18483/18483 [06:58<00:00, 44.13batch/s, fase=teste]

--------------------------------------------------------------------------------
Modelo: NCTD Base | Dataset: adult income | Entrada: image | Dados: original
Accuracy: 0.8493
F1: 0.6214
Precision: 0.7794
Recall: 0.5167
Tempo de treinamento: 418.84s
              precision    recall  f1-score   support

           0       0.86      0.95      0.91      7431
           1       0.78      0.52      0.62      2338

    accuracy                           0.85      9769
   macro avg       0.82      0.74      0.76      9769
weighted avg       0.84      0.85      0.84      9769

Pooling targets para adult income/NCTD Base: [(15, 15), (7, 7), (3, 3), (1, 1)]
Número de classes na saída: 2

adult income | NCTD Base | enriched: 100%|██████████| 28023/28023 [10:11<00:00, 45.82batch/s, fase=teste]

--------------------------------------------------------------------------------
Modelo: NCTD Base | Dataset: adult income | Entrada: image | Dados: enriched
Accuracy: 0.8427
F1: 0.6303
Precision: 0.7202
Recall: 0.5603
Tempo de treinamento: 611.55s
              precision    recall  f1-score   support

           0       0.87      0.93      0.90      7431
           1       0.72      0.56      0.63      2338

    accuracy                           0.84      9769
   macro avg       0.80      0.75      0.77      9769
weighted avg       0.83      0.84      0.84      9769

Pooling targets para adult income/NCTD Attention (SE): [(15, 15), (7, 7), (3, 3), (1, 1)]
Número de classes na saída: 2

adult income | NCTD Attention (SE) | original: 100%|██████████| 18483/18483 [07:02<00:00, 43.74batch/s, fase=teste]

--------------------------------------------------------------------------------
Modelo: NCTD Attention (SE) | Dataset: adult income | Entrada: image | Dados: original
Accuracy: 0.8495
F1: 0.6312
Precision: 0.7633
Recall: 0.5381
Tempo de treinamento: 422.54s
              precision    recall  f1-score   support

           0       0.87      0.95      0.91      7431
           1       0.76      0.54      0.63      2338

    accuracy                           0.85      9769
   macro avg       0.82      0.74      0.77      9769
weighted avg       0.84      0.85      0.84      9769

Pooling targets para adult income/NCTD Attention (SE): [(15, 15), (7, 7), (3, 3), (1, 1)]
Número de classes na saída: 2

adult income | NCTD Attention (SE) | enriched: 100%|██████████| 28023/28023 [10:54<00:00, 42.79batch/s, fase=teste]

--------------------------------------------------------------------------------
Modelo: NCTD Attention (SE) | Dataset: adult income | Entrada: image | Dados: enriched
Accuracy: 0.8513
F1: 0.6466
Precision: 0.7496
Recall: 0.5684
Tempo de treinamento: 654.95s
              precision    recall  f1-score   support

           0       0.87      0.94      0.91      7431
           1       0.75      0.57      0.65      2338

    accuracy                           0.85      9769
   macro avg       0.81      0.75      0.78      9769
weighted avg       0.84      0.85      0.84      9769

Pooling targets para adult income/NCTD Asymmetric Kernels: [(15, 15), (7, 7), (3, 3), (1, 1)]
Número de classes na saída: 2

adult income | NCTD Asymmetric Kernels | original: 100%|██████████| 18483/18483 [07:15<00:00, 42.44batch/s, fase=teste]

--------------------------------------------------------------------------------
Modelo: NCTD Asymmetric Kernels | Dataset: adult income | Entrada: image | Dados: original
Accuracy: 0.8510
F1: 0.6722
Precision: 0.7096
Recall: 0.6386
Tempo de treinamento: 435.52s
              precision    recall  f1-score   support

           0       0.89      0.92      0.90      7431
           1       0.71      0.64      0.67      2338

    accuracy                           0.85      9769
   macro avg       0.80      0.78      0.79      9769
weighted avg       0.85      0.85      0.85      9769

Pooling targets para adult income/NCTD Asymmetric Kernels: [(15, 15), (7, 7), (3, 3), (1, 1)]
Número de classes na saída: 2

adult income | NCTD Asymmetric Kernels | enriched: 100%|██████████| 28023/28023 [11:19<00:00, 41.23batch/s, fase=teste]

--------------------------------------------------------------------------------
Modelo: NCTD Asymmetric Kernels | Dataset: adult income | Entrada: image | Dados: enriched
Accuracy: 0.8136
F1: 0.6301
Precision: 0.6000
Recall: 0.6634
Tempo de treinamento: 679.71s
              precision    recall  f1-score   support

           0       0.89      0.86      0.88      7431
           1       0.60      0.66      0.63      2338

    accuracy                           0.81      9769
   macro avg       0.75      0.76      0.75      9769
weighted avg       0.82      0.81      0.82      9769

Pooling targets para adult income/NCTD Dilated Convolutions: [(15, 15), (7, 7), (3, 3), (1, 1)]
Número de classes na saída: 2

adult income | NCTD Dilated Convolutions | original: 100%|██████████| 18483/18483 [06:57<00:00, 44.27batch/s, fase=teste]

--------------------------------------------------------------------------------
Modelo: NCTD Dilated Convolutions | Dataset: adult income | Entrada: image | Dados: original
Accuracy: 0.8485
F1: 0.6324
Precision: 0.7541
Recall: 0.5445
Tempo de treinamento: 417.59s
              precision    recall  f1-score   support

           0       0.87      0.94      0.90      7431
           1       0.75      0.54      0.63      2338

    accuracy                           0.85      9769
   macro avg       0.81      0.74      0.77      9769
weighted avg       0.84      0.85      0.84      9769

Pooling targets para adult income/NCTD Dilated Convolutions: [(15, 15), (7, 7), (3, 3), (1, 1)]
Número de classes na saída: 2

adult income | NCTD Dilated Convolutions | enriched: 100%|██████████| 28023/28023 [09:58<00:00, 46.83batch/s, fase=teste]

--------------------------------------------------------------------------------
Modelo: NCTD Dilated Convolutions | Dataset: adult income | Entrada: image | Dados: enriched
Accuracy: 0.8444
F1: 0.6465
Precision: 0.7085
Recall: 0.5945
Tempo de treinamento: 598.42s
              precision    recall  f1-score   support

           0       0.88      0.92      0.90      7431
           1       0.71      0.59      0.65      2338

    accuracy                           0.84      9769
   macro avg       0.79      0.76      0.77      9769
weighted avg       0.84      0.84      0.84      9769

Pooling targets para adult income/NCTD Residual: [(15, 15), (7, 7), (3, 3), (1, 1)]
Número de classes na saída: 2

adult income | NCTD Residual | original: 100%|██████████| 18483/18483 [06:57<00:00, 44.26batch/s, fase=teste]

--------------------------------------------------------------------------------
Modelo: NCTD Residual | Dataset: adult income | Entrada: image | Dados: original
Accuracy: 0.8464
F1: 0.6370
Precision: 0.7329
Recall: 0.5633
Tempo de treinamento: 417.56s
              precision    recall  f1-score   support

           0       0.87      0.94      0.90      7431
           1       0.73      0.56      0.64      2338

    accuracy                           0.85      9769
   macro avg       0.80      0.75      0.77      9769
weighted avg       0.84      0.85      0.84      9769

Pooling targets para adult income/NCTD Residual: [(15, 15), (7, 7), (3, 3), (1, 1)]
Número de classes na saída: 2

adult income | NCTD Residual | enriched: 100%|██████████| 28023/28023 [10:38<00:00, 43.88batch/s, fase=teste]

--------------------------------------------------------------------------------
Modelo: NCTD Residual | Dataset: adult income | Entrada: image | Dados: enriched
Accuracy: 0.8481
F1: 0.6467
Precision: 0.7293
Recall: 0.5808
Tempo de treinamento: 638.51s
              precision    recall  f1-score   support

           0       0.88      0.93      0.90      7431
           1       0.73      0.58      0.65      2338

    accuracy                           0.85      9769
   macro avg       0.80      0.76      0.77      9769
weighted avg       0.84      0.85      0.84      9769


================================================================================
Iniciando experimentos para o dataset: student
================================================================================
--------------------------------------------------------------------------------
Modelo: XGBoost | Dataset: student | Entrada: tabular | Dados: original
Accuracy: 0.7751
F1: 0.7115
Precision: 0.7246
Recall: 0.7034
Tempo de treinamento: 0.55s
              precision    recall  f1-score   support

           0       0.81      0.74      0.77       284
           1       0.54      0.46      0.50       159
           2       0.82      0.91      0.86       442

    accuracy                           0.78       885
   macro avg       0.72      0.70      0.71       885
weighted avg       0.77      0.78      0.77       885

--------------------------------------------------------------------------------
Modelo: XGBoost | Dataset: student | Entrada: tabular | Dados: enriched
Accuracy: 0.7638
F1: 0.6909
Precision: 0.7123
Recall: 0.6808
Tempo de treinamento: 0.55s
              precision    recall  f1-score   support

           0       0.81      0.73      0.77       284
           1       0.53      0.40      0.45       159
           2       0.79      0.92      0.85       442

    accuracy                           0.76       885
   macro avg       0.71      0.68      0.69       885
weighted avg       0.75      0.76      0.75       885

Pooling targets para student/NCTD Base: [(15, 15), (7, 7), (3, 3), (1, 1)]
Número de classes na saída: 3

student | NCTD Base | original: 100%|██████████| 1694/1694 [01:49<00:00, 15.45batch/s, fase=teste]

--------------------------------------------------------------------------------
Modelo: NCTD Base | Dataset: student | Entrada: image | Dados: original
Accuracy: 0.6169
F1: 0.5891
Precision: 0.6055
Recall: 0.6032
Tempo de treinamento: 109.66s
              precision    recall  f1-score   support

           0       0.71      0.68      0.69       284
           1       0.29      0.52      0.37       159
           2       0.82      0.61      0.70       442

    accuracy                           0.62       885
   macro avg       0.61      0.60      0.59       885
weighted avg       0.69      0.62      0.64       885

Pooling targets para student/NCTD Base: [(15, 15), (7, 7), (3, 3), (1, 1)]
Número de classes na saída: 3

student | NCTD Base | enriched: 100%|██████████| 2504/2504 [02:43<00:00, 15.33batch/s, fase=teste]

--------------------------------------------------------------------------------
Modelo: NCTD Base | Dataset: student | Entrada: image | Dados: enriched
Accuracy: 0.4384
F1: 0.4433
Precision: 0.5499
Recall: 0.5174
Tempo de treinamento: 163.32s
              precision    recall  f1-score   support

           0       0.63      0.60      0.61       284
           1       0.24      0.72      0.36       159
           2       0.79      0.23      0.36       442

    accuracy                           0.44       885
   macro avg       0.55      0.52      0.44       885
weighted avg       0.64      0.44      0.44       885

Pooling targets para student/NCTD Attention (SE): [(15, 15), (7, 7), (3, 3), (1, 1)]
Número de classes na saída: 3

student | NCTD Attention (SE) | original: 100%|██████████| 1694/1694 [01:56<00:00, 14.59batch/s, fase=teste]

--------------------------------------------------------------------------------
Modelo: NCTD Attention (SE) | Dataset: student | Entrada: image | Dados: original
Accuracy: 0.7153
F1: 0.6093
Precision: 0.6281
Recall: 0.6060
Tempo de treinamento: 116.10s
              precision    recall  f1-score   support

           0       0.77      0.65      0.70       284
           1       0.35      0.24      0.28       159
           2       0.76      0.93      0.84       442

    accuracy                           0.72       885
   macro avg       0.63      0.61      0.61       885
weighted avg       0.69      0.72      0.70       885

Pooling targets para student/NCTD Attention (SE): [(15, 15), (7, 7), (3, 3), (1, 1)]
Número de classes na saída: 3

student | NCTD Attention (SE) | enriched: 100%|██████████| 2504/2504 [02:54<00:00, 14.36batch/s, fase=teste]

--------------------------------------------------------------------------------
Modelo: NCTD Attention (SE) | Dataset: student | Entrada: image | Dados: enriched
Accuracy: 0.4689
F1: 0.4788
Precision: 0.6212
Recall: 0.5445
Tempo de treinamento: 174.33s
              precision    recall  f1-score   support

           0       0.75      0.70      0.73       284
           1       0.22      0.69      0.33       159
           2       0.89      0.24      0.38       442

    accuracy                           0.47       885
   macro avg       0.62      0.54      0.48       885
weighted avg       0.73      0.47      0.48       885

Pooling targets para student/NCTD Asymmetric Kernels: [(15, 15), (7, 7), (3, 3), (1, 1)]
Número de classes na saída: 3

student | NCTD Asymmetric Kernels | original: 100%|██████████| 1694/1694 [02:09<00:00, 13.08batch/s, fase=teste]

--------------------------------------------------------------------------------
Modelo: NCTD Asymmetric Kernels | Dataset: student | Entrada: image | Dados: original
Accuracy: 0.6768
F1: 0.6261
Precision: 0.6315
Recall: 0.6351
Tempo de treinamento: 129.47s
              precision    recall  f1-score   support

           0       0.72      0.80      0.76       284
           1       0.30      0.42      0.35       159
           2       0.87      0.69      0.77       442

    accuracy                           0.68       885
   macro avg       0.63      0.64      0.63       885
weighted avg       0.72      0.68      0.69       885

Pooling targets para student/NCTD Asymmetric Kernels: [(15, 15), (7, 7), (3, 3), (1, 1)]
Número de classes na saída: 3

student | NCTD Asymmetric Kernels | enriched: 100%|██████████| 2504/2504 [03:13<00:00, 12.93batch/s, fase=teste]

--------------------------------------------------------------------------------
Modelo: NCTD Asymmetric Kernels | Dataset: student | Entrada: image | Dados: enriched
Accuracy: 0.7379
F1: 0.6171
Precision: 0.6652
Recall: 0.6157
Tempo de treinamento: 193.64s
              precision    recall  f1-score   support

           0       0.83      0.71      0.76       284
           1       0.43      0.18      0.26       159
           2       0.74      0.96      0.83       442

    accuracy                           0.74       885
   macro avg       0.67      0.62      0.62       885
weighted avg       0.71      0.74      0.71       885

Pooling targets para student/NCTD Dilated Convolutions: [(15, 15), (7, 7), (3, 3), (1, 1)]
Número de classes na saída: 3

student | NCTD Dilated Convolutions | original: 100%|██████████| 1694/1694 [01:48<00:00, 15.67batch/s, fase=teste]

--------------------------------------------------------------------------------
Modelo: NCTD Dilated Convolutions | Dataset: student | Entrada: image | Dados: original
Accuracy: 0.7006
F1: 0.5307
Precision: 0.6484
Recall: 0.5630
Tempo de treinamento: 108.09s
              precision    recall  f1-score   support

           0       0.70      0.72      0.71       284
           1       0.54      0.04      0.08       159
           2       0.70      0.92      0.80       442

    accuracy                           0.70       885
   macro avg       0.65      0.56      0.53       885
weighted avg       0.67      0.70      0.64       885

Pooling targets para student/NCTD Dilated Convolutions: [(15, 15), (7, 7), (3, 3), (1, 1)]
Número de classes na saída: 3

student | NCTD Dilated Convolutions | enriched: 100%|██████████| 2504/2504 [02:42<00:00, 15.44batch/s, fase=teste]

--------------------------------------------------------------------------------
Modelo: NCTD Dilated Convolutions | Dataset: student | Entrada: image | Dados: enriched
Accuracy: 0.6701
F1: 0.6311
Precision: 0.6502
Recall: 0.6370
Tempo de treinamento: 162.13s
              precision    recall  f1-score   support

           0       0.81      0.61      0.70       284
           1       0.35      0.55      0.42       159
           2       0.79      0.75      0.77       442

    accuracy                           0.67       885
   macro avg       0.65      0.64      0.63       885
weighted avg       0.72      0.67      0.69       885

Pooling targets para student/NCTD Residual: [(15, 15), (7, 7), (3, 3), (1, 1)]
Número de classes na saída: 3

student | NCTD Residual | original: 100%|██████████| 1694/1694 [02:00<00:00, 14.08batch/s, fase=teste]

--------------------------------------------------------------------------------
Modelo: NCTD Residual | Dataset: student | Entrada: image | Dados: original
Accuracy: 0.6644
F1: 0.5066
Precision: 0.5333
Recall: 0.5355
Tempo de treinamento: 120.32s
              precision    recall  f1-score   support

           0       0.67      0.69      0.68       284
           1       0.25      0.04      0.07       159
           2       0.68      0.87      0.77       442

    accuracy                           0.66       885
   macro avg       0.53      0.54      0.51       885
weighted avg       0.60      0.66      0.61       885

Pooling targets para student/NCTD Residual: [(15, 15), (7, 7), (3, 3), (1, 1)]
Número de classes na saída: 3

student | NCTD Residual | enriched: 100%|██████████| 2504/2504 [03:01<00:00, 13.81batch/s, fase=teste]

--------------------------------------------------------------------------------
Modelo: NCTD Residual | Dataset: student | Entrada: image | Dados: enriched
Accuracy: 0.6350
F1: 0.5462
Precision: 0.5578
Recall: 0.5419
Tempo de treinamento: 181.31s
              precision    recall  f1-score   support

           0       0.71      0.57      0.64       284
           1       0.24      0.23      0.24       159
           2       0.72      0.82      0.77       442

    accuracy                           0.64       885
   macro avg       0.56      0.54      0.55       885
weighted avg       0.63      0.64      0.63       885


================================================================================
Iniciando experimentos para o dataset: statlog
================================================================================
--------------------------------------------------------------------------------
Modelo: XGBoost | Dataset: statlog | Entrada: tabular | Dados: original
Accuracy: 0.9984
F1: 0.6816
Precision: 0.6931
Recall: 0.6721
Tempo de treinamento: 1.08s
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      9117
           1       1.00      1.00      1.00        10
           2       0.86      0.71      0.77        34
           3       1.00      1.00      1.00      1781
           4       1.00      1.00      1.00       653
           5       0.00      0.00      0.00         2
           6       0.00      0.00      0.00         3

    accuracy                           1.00     11600
   macro avg       0.69      0.67      0.68     11600
weighted avg       1.00      1.00      1.00     11600

--------------------------------------------------------------------------------
Modelo: XGBoost | Dataset: statlog | Entrada: tabular | Dados: enriched
Accuracy: 0.9969
F1: 0.5261
Precision: 0.5692
Recall: 0.5037
Tempo de treinamento: 1.78s
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      9117
           1       0.00      0.00      0.00        10
           2       1.00      0.53      0.69        34
           3       0.99      1.00      0.99      1781
           4       1.00      1.00      1.00       653
           5       0.00      0.00      0.00         2
           6       0.00      0.00      0.00         3

    accuracy                           1.00     11600
   macro avg       0.57      0.50      0.53     11600
weighted avg       1.00      1.00      1.00     11600

Pooling targets para statlog/NCTD Base: [(14, 14), (7, 7), (3, 3), (1, 1)]
Número de classes na saída: 7

statlog | NCTD Base | original: 100%|██████████| 21932/21932 [01:05<00:00, 334.75batch/s, fase=teste]

--------------------------------------------------------------------------------
Modelo: NCTD Base | Dataset: statlog | Entrada: image | Dados: original
Accuracy: 0.9979
F1: 0.6536
Precision: 0.7129
Recall: 0.6183
Tempo de treinamento: 65.52s
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      9117
           1       1.00      0.80      0.89        10
           2       1.00      0.53      0.69        34
           3       1.00      1.00      1.00      1781
           4       1.00      1.00      1.00       653
           5       0.00      0.00      0.00         2
           6       0.00      0.00      0.00         3

    accuracy                           1.00     11600
   macro avg       0.71      0.62      0.65     11600
weighted avg       1.00      1.00      1.00     11600

Pooling targets para statlog/NCTD Base: [(14, 14), (7, 7), (3, 3), (1, 1)]
Número de classes na saída: 7

statlog | NCTD Base | enriched: 100%|██████████| 119852/119852 [05:59<00:00, 332.94batch/s, fase=teste]

--------------------------------------------------------------------------------
Modelo: NCTD Base | Dataset: statlog | Entrada: image | Dados: enriched
Accuracy: 0.9976
F1: 0.6184
Precision: 0.6582
Recall: 0.5936
Tempo de treinamento: 359.99s
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      9117
           1       0.67      0.60      0.63        10
           2       0.95      0.56      0.70        34
           3       1.00      1.00      1.00      1781
           4       1.00      1.00      1.00       653
           5       0.00      0.00      0.00         2
           6       0.00      0.00      0.00         3

    accuracy                           1.00     11600
   macro avg       0.66      0.59      0.62     11600
weighted avg       1.00      1.00      1.00     11600

Pooling targets para statlog/NCTD Attention (SE): [(14, 14), (7, 7), (3, 3), (1, 1)]
Número de classes na saída: 7

statlog | NCTD Attention (SE) | original: 100%|██████████| 21932/21932 [01:27<00:00, 249.95batch/s, fase=teste]

--------------------------------------------------------------------------------
Modelo: NCTD Attention (SE) | Dataset: statlog | Entrada: image | Dados: original
Accuracy: 0.9981
F1: 0.6622
Precision: 0.7131
Recall: 0.6328
Tempo de treinamento: 87.75s
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      9117
           1       1.00      0.90      0.95        10
           2       1.00      0.53      0.69        34
           3       1.00      1.00      1.00      1781
           4       1.00      1.00      1.00       653
           5       0.00      0.00      0.00         2
           6       0.00      0.00      0.00         3

    accuracy                           1.00     11600
   macro avg       0.71      0.63      0.66     11600
weighted avg       1.00      1.00      1.00     11600

Pooling targets para statlog/NCTD Attention (SE): [(14, 14), (7, 7), (3, 3), (1, 1)]
Número de classes na saída: 7

statlog | NCTD Attention (SE) | enriched: 100%|██████████| 119852/119852 [08:02<00:00, 248.45batch/s, fase=teste]

--------------------------------------------------------------------------------
Modelo: NCTD Attention (SE) | Dataset: statlog | Entrada: image | Dados: enriched
Accuracy: 0.9979
F1: 0.6638
Precision: 0.7061
Recall: 0.6367
Tempo de treinamento: 482.40s
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      9117
           1       1.00      0.90      0.95        10
           2       0.95      0.56      0.70        34
           3       1.00      1.00      1.00      1781
           4       1.00      1.00      1.00       653
           5       0.00      0.00      0.00         2
           6       0.00      0.00      0.00         3

    accuracy                           1.00     11600
   macro avg       0.71      0.64      0.66     11600
weighted avg       1.00      1.00      1.00     11600

Pooling targets para statlog/NCTD Asymmetric Kernels: [(14, 14), (7, 7), (3, 3), (1, 1)]
Número de classes na saída: 7

statlog | NCTD Asymmetric Kernels | original: 100%|██████████| 21932/21932 [01:23<00:00, 261.37batch/s, fase=teste]

--------------------------------------------------------------------------------
Modelo: NCTD Asymmetric Kernels | Dataset: statlog | Entrada: image | Dados: original
Accuracy: 0.9982
F1: 0.6698
Precision: 0.7132
Recall: 0.6471
Tempo de treinamento: 83.91s
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      9117
           1       1.00      1.00      1.00        10
           2       1.00      0.53      0.69        34
           3       1.00      1.00      1.00      1781
           4       1.00      1.00      1.00       653
           5       0.00      0.00      0.00         2
           6       0.00      0.00      0.00         3

    accuracy                           1.00     11600
   macro avg       0.71      0.65      0.67     11600
weighted avg       1.00      1.00      1.00     11600

Pooling targets para statlog/NCTD Asymmetric Kernels: [(14, 14), (7, 7), (3, 3), (1, 1)]
Número de classes na saída: 7

statlog | NCTD Asymmetric Kernels | enriched: 100%|██████████| 119852/119852 [07:39<00:00, 260.65batch/s, fase=teste]

--------------------------------------------------------------------------------
Modelo: NCTD Asymmetric Kernels | Dataset: statlog | Entrada: image | Dados: enriched
Accuracy: 0.9975
F1: 0.6321
Precision: 0.6772
Recall: 0.6199
Tempo de treinamento: 459.84s
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      9117
           1       0.75      0.90      0.82        10
           2       1.00      0.44      0.61        34
           3       0.99      1.00      1.00      1781
           4       1.00      1.00      1.00       653
           5       0.00      0.00      0.00         2
           6       0.00      0.00      0.00         3

    accuracy                           1.00     11600
   macro avg       0.68      0.62      0.63     11600
weighted avg       1.00      1.00      1.00     11600

Pooling targets para statlog/NCTD Dilated Convolutions: [(14, 14), (7, 7), (3, 3), (1, 1)]
Número de classes na saída: 7

statlog | NCTD Dilated Convolutions | original: 100%|██████████| 21932/21932 [01:05<00:00, 335.26batch/s, fase=teste]

--------------------------------------------------------------------------------
Modelo: NCTD Dilated Convolutions | Dataset: statlog | Entrada: image | Dados: original
Accuracy: 0.9965
F1: 0.5961
Precision: 0.6496
Recall: 0.6032
Tempo de treinamento: 65.42s
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      9117
           1       0.56      0.90      0.69        10
           2       1.00      0.32      0.49        34
           3       0.99      1.00      0.99      1781
           4       1.00      1.00      1.00       653
           5       0.00      0.00      0.00         2
           6       0.00      0.00      0.00         3

    accuracy                           1.00     11600
   macro avg       0.65      0.60      0.60     11600
weighted avg       1.00      1.00      1.00     11600

Pooling targets para statlog/NCTD Dilated Convolutions: [(14, 14), (7, 7), (3, 3), (1, 1)]
Número de classes na saída: 7

statlog | NCTD Dilated Convolutions | enriched: 100%|██████████| 119852/119852 [05:59<00:00, 333.19batch/s, fase=teste]

--------------------------------------------------------------------------------
Modelo: NCTD Dilated Convolutions | Dataset: statlog | Entrada: image | Dados: enriched
Accuracy: 0.9961
F1: 0.5964
Precision: 0.6582
Recall: 0.5639
Tempo de treinamento: 359.71s
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      9117
           1       0.62      0.50      0.56        10
           2       1.00      0.47      0.64        34
           3       0.99      1.00      0.99      1781
           4       1.00      0.98      0.99       653
           5       0.00      0.00      0.00         2
           6       0.00      0.00      0.00         3

    accuracy                           1.00     11600
   macro avg       0.66      0.56      0.60     11600
weighted avg       1.00      1.00      1.00     11600

Pooling targets para statlog/NCTD Residual: [(14, 14), (7, 7), (3, 3), (1, 1)]
Número de classes na saída: 7

statlog | NCTD Residual | original: 100%|██████████| 21932/21932 [01:21<00:00, 269.42batch/s, fase=teste]

--------------------------------------------------------------------------------
Modelo: NCTD Residual | Dataset: statlog | Entrada: image | Dados: original
Accuracy: 0.9979
F1: 0.6538
Precision: 0.7131
Recall: 0.6185
Tempo de treinamento: 81.41s
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      9117
           1       1.00      0.80      0.89        10
           2       1.00      0.53      0.69        34
           3       0.99      1.00      1.00      1781
           4       1.00      1.00      1.00       653
           5       0.00      0.00      0.00         2
           6       0.00      0.00      0.00         3

    accuracy                           1.00     11600
   macro avg       0.71      0.62      0.65     11600
weighted avg       1.00      1.00      1.00     11600

Pooling targets para statlog/NCTD Residual: [(14, 14), (7, 7), (3, 3), (1, 1)]
Número de classes na saída: 7

statlog | NCTD Residual | enriched: 100%|██████████| 119852/119852 [07:25<00:00, 269.10batch/s, fase=teste]

--------------------------------------------------------------------------------
Modelo: NCTD Residual | Dataset: statlog | Entrada: image | Dados: enriched
Accuracy: 0.9972
F1: 0.6011
Precision: 0.6505
Recall: 0.6071
Tempo de treinamento: 445.44s
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      9117
           1       0.56      0.90      0.69        10
           2       1.00      0.35      0.52        34
           3       1.00      1.00      1.00      1781
           4       1.00      1.00      1.00       653
           5       0.00      0.00      0.00         2
           6       0.00      0.00      0.00         3

    accuracy                           1.00     11600
   macro avg       0.65      0.61      0.60     11600
weighted avg       1.00      1.00      1.00     11600


================================================================================
Iniciando experimentos para o dataset: maintenance
================================================================================
--------------------------------------------------------------------------------
Modelo: XGBoost | Dataset: maintenance | Entrada: tabular | Dados: original
Accuracy: 0.9885
F1: 0.8099
Precision: 0.9245
Recall: 0.7206
Tempo de treinamento: 0.17s
              precision    recall  f1-score   support

           0       0.99      1.00      0.99      1932
           1       0.92      0.72      0.81        68

    accuracy                           0.99      2000
   macro avg       0.96      0.86      0.90      2000
weighted avg       0.99      0.99      0.99      2000

--------------------------------------------------------------------------------
Modelo: XGBoost | Dataset: maintenance | Entrada: tabular | Dados: enriched
Accuracy: 0.9695
F1: 0.6013
Precision: 0.5412
Recall: 0.6765
Tempo de treinamento: 0.18s
              precision    recall  f1-score   support

           0       0.99      0.98      0.98      1932
           1       0.54      0.68      0.60        68

    accuracy                           0.97      2000
   macro avg       0.76      0.83      0.79      2000
weighted avg       0.97      0.97      0.97      2000

Pooling targets para maintenance/NCTD Base: [(12, 12), (6, 6), (3, 3), (1, 1)]
Número de classes na saída: 2

maintenance | NCTD Base | original: 100%|██████████| 3782/3782 [00:10<00:00, 348.76batch/s, fase=teste]

--------------------------------------------------------------------------------
Modelo: NCTD Base | Dataset: maintenance | Entrada: image | Dados: original
Accuracy: 0.9790
F1: 0.7042
Precision: 0.6757
Recall: 0.7353
Tempo de treinamento: 10.85s
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      1932
           1       0.68      0.74      0.70        68

    accuracy                           0.98      2000
   macro avg       0.83      0.86      0.85      2000
weighted avg       0.98      0.98      0.98      2000

Pooling targets para maintenance/NCTD Base: [(12, 12), (6, 6), (3, 3), (1, 1)]
Número de classes na saída: 2

maintenance | NCTD Base | enriched: 100%|██████████| 7292/7292 [00:20<00:00, 350.93batch/s, fase=teste]

--------------------------------------------------------------------------------
Modelo: NCTD Base | Dataset: maintenance | Entrada: image | Dados: enriched
Accuracy: 0.9685
F1: 0.6087
Precision: 0.5269
Recall: 0.7206
Tempo de treinamento: 20.78s
              precision    recall  f1-score   support

           0       0.99      0.98      0.98      1932
           1       0.53      0.72      0.61        68

    accuracy                           0.97      2000
   macro avg       0.76      0.85      0.80      2000
weighted avg       0.97      0.97      0.97      2000

Pooling targets para maintenance/NCTD Attention (SE): [(12, 12), (6, 6), (3, 3), (1, 1)]
Número de classes na saída: 2

maintenance | NCTD Attention (SE) | original: 100%|██████████| 3782/3782 [00:15<00:00, 251.75batch/s, fase=teste]

--------------------------------------------------------------------------------
Modelo: NCTD Attention (SE) | Dataset: maintenance | Entrada: image | Dados: original
Accuracy: 0.9770
F1: 0.6892
Precision: 0.6375
Recall: 0.7500
Tempo de treinamento: 15.02s
              precision    recall  f1-score   support

           0       0.99      0.98      0.99      1932
           1       0.64      0.75      0.69        68

    accuracy                           0.98      2000
   macro avg       0.81      0.87      0.84      2000
weighted avg       0.98      0.98      0.98      2000

Pooling targets para maintenance/NCTD Attention (SE): [(12, 12), (6, 6), (3, 3), (1, 1)]
Número de classes na saída: 2

maintenance | NCTD Attention (SE) | enriched: 100%|██████████| 7292/7292 [00:28<00:00, 252.77batch/s, fase=teste]

--------------------------------------------------------------------------------
Modelo: NCTD Attention (SE) | Dataset: maintenance | Entrada: image | Dados: enriched
Accuracy: 0.9715
F1: 0.6369
Precision: 0.5618
Recall: 0.7353
Tempo de treinamento: 28.85s
              precision    recall  f1-score   support

           0       0.99      0.98      0.99      1932
           1       0.56      0.74      0.64        68

    accuracy                           0.97      2000
   macro avg       0.78      0.86      0.81      2000
weighted avg       0.98      0.97      0.97      2000

Pooling targets para maintenance/NCTD Asymmetric Kernels: [(12, 12), (6, 6), (3, 3), (1, 1)]
Número de classes na saída: 2

maintenance | NCTD Asymmetric Kernels | original: 100%|██████████| 3782/3782 [00:13<00:00, 285.80batch/s, fase=teste]

--------------------------------------------------------------------------------
Modelo: NCTD Asymmetric Kernels | Dataset: maintenance | Entrada: image | Dados: original
Accuracy: 0.9810
F1: 0.7246
Precision: 0.7143
Recall: 0.7353
Tempo de treinamento: 13.23s
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      1932
           1       0.71      0.74      0.72        68

    accuracy                           0.98      2000
   macro avg       0.85      0.86      0.86      2000
weighted avg       0.98      0.98      0.98      2000

Pooling targets para maintenance/NCTD Asymmetric Kernels: [(12, 12), (6, 6), (3, 3), (1, 1)]
Número de classes na saída: 2

maintenance | NCTD Asymmetric Kernels | enriched: 100%|██████████| 7292/7292 [00:25<00:00, 285.09batch/s, fase=teste]

--------------------------------------------------------------------------------
Modelo: NCTD Asymmetric Kernels | Dataset: maintenance | Entrada: image | Dados: enriched
Accuracy: 0.9770
F1: 0.6462
Precision: 0.6774
Recall: 0.6176
Tempo de treinamento: 25.58s
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      1932
           1       0.68      0.62      0.65        68

    accuracy                           0.98      2000
   macro avg       0.83      0.80      0.82      2000
weighted avg       0.98      0.98      0.98      2000

Pooling targets para maintenance/NCTD Dilated Convolutions: [(12, 12), (6, 6), (3, 3), (1, 1)]
Número de classes na saída: 2

maintenance | NCTD Dilated Convolutions | original: 100%|██████████| 3782/3782 [00:10<00:00, 350.15batch/s, fase=teste]

--------------------------------------------------------------------------------
Modelo: NCTD Dilated Convolutions | Dataset: maintenance | Entrada: image | Dados: original
Accuracy: 0.9755
F1: 0.6839
Precision: 0.6092
Recall: 0.7794
Tempo de treinamento: 10.80s
              precision    recall  f1-score   support

           0       0.99      0.98      0.99      1932
           1       0.61      0.78      0.68        68

    accuracy                           0.98      2000
   macro avg       0.80      0.88      0.84      2000
weighted avg       0.98      0.98      0.98      2000

Pooling targets para maintenance/NCTD Dilated Convolutions: [(12, 12), (6, 6), (3, 3), (1, 1)]
Número de classes na saída: 2

maintenance | NCTD Dilated Convolutions | enriched: 100%|██████████| 7292/7292 [00:20<00:00, 355.57batch/s, fase=teste]

--------------------------------------------------------------------------------
Modelo: NCTD Dilated Convolutions | Dataset: maintenance | Entrada: image | Dados: enriched
Accuracy: 0.9675
F1: 0.5912
Precision: 0.5165
Recall: 0.6912
Tempo de treinamento: 20.51s
              precision    recall  f1-score   support

           0       0.99      0.98      0.98      1932
           1       0.52      0.69      0.59        68

    accuracy                           0.97      2000
   macro avg       0.75      0.83      0.79      2000
weighted avg       0.97      0.97      0.97      2000

Pooling targets para maintenance/NCTD Residual: [(12, 12), (6, 6), (3, 3), (1, 1)]
Número de classes na saída: 2

maintenance | NCTD Residual | original: 100%|██████████| 3782/3782 [00:13<00:00, 290.67batch/s, fase=teste]

--------------------------------------------------------------------------------
Modelo: NCTD Residual | Dataset: maintenance | Entrada: image | Dados: original
Accuracy: 0.9780
F1: 0.7105
Precision: 0.6429
Recall: 0.7941
Tempo de treinamento: 13.01s
              precision    recall  f1-score   support

           0       0.99      0.98      0.99      1932
           1       0.64      0.79      0.71        68

    accuracy                           0.98      2000
   macro avg       0.82      0.89      0.85      2000
weighted avg       0.98      0.98      0.98      2000

Pooling targets para maintenance/NCTD Residual: [(12, 12), (6, 6), (3, 3), (1, 1)]
Número de classes na saída: 2

maintenance | NCTD Residual | enriched: 100%|██████████| 7292/7292 [00:24<00:00, 294.01batch/s, fase=teste]

--------------------------------------------------------------------------------
Modelo: NCTD Residual | Dataset: maintenance | Entrada: image | Dados: enriched
Accuracy: 0.9755
F1: 0.6370
Precision: 0.6418
Recall: 0.6324
Tempo de treinamento: 24.80s
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      1932
           1       0.64      0.63      0.64        68

    accuracy                           0.98      2000
   macro avg       0.81      0.81      0.81      2000
weighted avg       0.98      0.98      0.98      2000


================================================================================
Iniciando experimentos para o dataset: stroke
================================================================================
--------------------------------------------------------------------------------
Modelo: XGBoost | Dataset: stroke | Entrada: tabular | Dados: original
Accuracy: 0.9501
F1: 0.0727
Precision: 0.4000
Recall: 0.0400
Tempo de treinamento: 0.17s
              precision    recall  f1-score   support

           0       0.95      1.00      0.97       972
           1       0.40      0.04      0.07        50

    accuracy                           0.95      1022
   macro avg       0.68      0.52      0.52      1022
weighted avg       0.93      0.95      0.93      1022

--------------------------------------------------------------------------------
Modelo: XGBoost | Dataset: stroke | Entrada: tabular | Dados: enriched
Accuracy: 0.9472
F1: 0.0690
Precision: 0.2500
Recall: 0.0400
Tempo de treinamento: 0.17s
              precision    recall  f1-score   support

           0       0.95      0.99      0.97       972
           1       0.25      0.04      0.07        50

    accuracy                           0.95      1022
   macro avg       0.60      0.52      0.52      1022
weighted avg       0.92      0.95      0.93      1022

Pooling targets para stroke/NCTD Base: [(15, 15), (7, 7), (3, 3), (1, 1)]
Número de classes na saída: 2

stroke | NCTD Base | original: 100%|██████████| 1936/1936 [00:20<00:00, 92.89batch/s, fase=teste]

--------------------------------------------------------------------------------
Modelo: NCTD Base | Dataset: stroke | Entrada: image | Dados: original
Accuracy: 0.9511
F1: 0.0000
Precision: 0.0000
Recall: 0.0000
Tempo de treinamento: 20.84s
              precision    recall  f1-score   support

           0       0.95      1.00      0.97       972
           1       0.00      0.00      0.00        50

    accuracy                           0.95      1022
   macro avg       0.48      0.50      0.49      1022
weighted avg       0.90      0.95      0.93      1022

Pooling targets para stroke/NCTD Base: [(15, 15), (7, 7), (3, 3), (1, 1)]
Número de classes na saída: 2

stroke | NCTD Base | enriched: 100%|██████████| 3676/3676 [00:39<00:00, 93.71batch/s, fase=teste]

--------------------------------------------------------------------------------
Modelo: NCTD Base | Dataset: stroke | Entrada: image | Dados: enriched
Accuracy: 0.8885
F1: 0.1857
Precision: 0.1444
Recall: 0.2600
Tempo de treinamento: 39.23s
              precision    recall  f1-score   support

           0       0.96      0.92      0.94       972
           1       0.14      0.26      0.19        50

    accuracy                           0.89      1022
   macro avg       0.55      0.59      0.56      1022
weighted avg       0.92      0.89      0.90      1022

Pooling targets para stroke/NCTD Attention (SE): [(15, 15), (7, 7), (3, 3), (1, 1)]
Número de classes na saída: 2

stroke | NCTD Attention (SE) | original: 100%|██████████| 1936/1936 [00:22<00:00, 85.60batch/s, fase=teste]

--------------------------------------------------------------------------------
Modelo: NCTD Attention (SE) | Dataset: stroke | Entrada: image | Dados: original
Accuracy: 0.9511
F1: 0.0000
Precision: 0.0000
Recall: 0.0000
Tempo de treinamento: 22.62s
              precision    recall  f1-score   support

           0       0.95      1.00      0.97       972
           1       0.00      0.00      0.00        50

    accuracy                           0.95      1022
   macro avg       0.48      0.50      0.49      1022
weighted avg       0.90      0.95      0.93      1022

Pooling targets para stroke/NCTD Attention (SE): [(15, 15), (7, 7), (3, 3), (1, 1)]
Número de classes na saída: 2

stroke | NCTD Attention (SE) | enriched: 100%|██████████| 3676/3676 [00:42<00:00, 85.80batch/s, fase=teste]

--------------------------------------------------------------------------------
Modelo: NCTD Attention (SE) | Dataset: stroke | Entrada: image | Dados: enriched
Accuracy: 0.8327
F1: 0.1818
Precision: 0.1195
Recall: 0.3800
Tempo de treinamento: 42.84s
              precision    recall  f1-score   support

           0       0.96      0.86      0.91       972
           1       0.12      0.38      0.18        50

    accuracy                           0.83      1022
   macro avg       0.54      0.62      0.54      1022
weighted avg       0.92      0.83      0.87      1022

Pooling targets para stroke/NCTD Asymmetric Kernels: [(15, 15), (7, 7), (3, 3), (1, 1)]
Número de classes na saída: 2

stroke | NCTD Asymmetric Kernels | original: 100%|██████████| 1936/1936 [00:23<00:00, 83.80batch/s, fase=teste]

--------------------------------------------------------------------------------
Modelo: NCTD Asymmetric Kernels | Dataset: stroke | Entrada: image | Dados: original
Accuracy: 0.9511
F1: 0.0000
Precision: 0.0000
Recall: 0.0000
Tempo de treinamento: 23.10s
              precision    recall  f1-score   support

           0       0.95      1.00      0.97       972
           1       0.00      0.00      0.00        50

    accuracy                           0.95      1022
   macro avg       0.48      0.50      0.49      1022
weighted avg       0.90      0.95      0.93      1022

Pooling targets para stroke/NCTD Asymmetric Kernels: [(15, 15), (7, 7), (3, 3), (1, 1)]
Número de classes na saída: 2

stroke | NCTD Asymmetric Kernels | enriched: 100%|██████████| 3676/3676 [00:43<00:00, 83.80batch/s, fase=teste]

--------------------------------------------------------------------------------
Modelo: NCTD Asymmetric Kernels | Dataset: stroke | Entrada: image | Dados: enriched
Accuracy: 0.9061
F1: 0.1724
Precision: 0.1515
Recall: 0.2000
Tempo de treinamento: 43.87s
              precision    recall  f1-score   support

           0       0.96      0.94      0.95       972
           1       0.15      0.20      0.17        50

    accuracy                           0.91      1022
   macro avg       0.55      0.57      0.56      1022
weighted avg       0.92      0.91      0.91      1022

Pooling targets para stroke/NCTD Dilated Convolutions: [(15, 15), (7, 7), (3, 3), (1, 1)]
Número de classes na saída: 2

stroke | NCTD Dilated Convolutions | original: 100%|██████████| 1936/1936 [00:20<00:00, 93.76batch/s, fase=teste]

--------------------------------------------------------------------------------
Modelo: NCTD Dilated Convolutions | Dataset: stroke | Entrada: image | Dados: original
Accuracy: 0.9511
F1: 0.0000
Precision: 0.0000
Recall: 0.0000
Tempo de treinamento: 20.65s
              precision    recall  f1-score   support

           0       0.95      1.00      0.97       972
           1       0.00      0.00      0.00        50

    accuracy                           0.95      1022
   macro avg       0.48      0.50      0.49      1022
weighted avg       0.90      0.95      0.93      1022

Pooling targets para stroke/NCTD Dilated Convolutions: [(15, 15), (7, 7), (3, 3), (1, 1)]
Número de classes na saída: 2

stroke | NCTD Dilated Convolutions | enriched: 100%|██████████| 3676/3676 [00:39<00:00, 93.64batch/s, fase=teste]

--------------------------------------------------------------------------------
Modelo: NCTD Dilated Convolutions | Dataset: stroke | Entrada: image | Dados: enriched
Accuracy: 0.8904
F1: 0.1765
Precision: 0.1395
Recall: 0.2400
Tempo de treinamento: 39.26s
              precision    recall  f1-score   support

           0       0.96      0.92      0.94       972
           1       0.14      0.24      0.18        50

    accuracy                           0.89      1022
   macro avg       0.55      0.58      0.56      1022
weighted avg       0.92      0.89      0.90      1022

Pooling targets para stroke/NCTD Residual: [(15, 15), (7, 7), (3, 3), (1, 1)]
Número de classes na saída: 2

stroke | NCTD Residual | original: 100%|██████████| 1936/1936 [00:22<00:00, 85.79batch/s, fase=teste]

--------------------------------------------------------------------------------
Modelo: NCTD Residual | Dataset: stroke | Entrada: image | Dados: original
Accuracy: 0.9511
F1: 0.0000
Precision: 0.0000
Recall: 0.0000
Tempo de treinamento: 22.57s
              precision    recall  f1-score   support

           0       0.95      1.00      0.97       972
           1       0.00      0.00      0.00        50

    accuracy                           0.95      1022
   macro avg       0.48      0.50      0.49      1022
weighted avg       0.90      0.95      0.93      1022

Pooling targets para stroke/NCTD Residual: [(15, 15), (7, 7), (3, 3), (1, 1)]
Número de classes na saída: 2

stroke | NCTD Residual | enriched: 100%|██████████| 3676/3676 [00:42<00:00, 85.73batch/s, fase=teste]

--------------------------------------------------------------------------------
Modelo: NCTD Residual | Dataset: stroke | Entrada: image | Dados: enriched
Accuracy: 0.8796
F1: 0.1854
Precision: 0.1386
Recall: 0.2800
Tempo de treinamento: 42.88s
              precision    recall  f1-score   support

           0       0.96      0.91      0.94       972
           1       0.14      0.28      0.19        50

    accuracy                           0.88      1022
   macro avg       0.55      0.60      0.56      1022
weighted avg       0.92      0.88      0.90      1022

Experimentos executados nesta sessão: 60
Experimentos pulados por já existirem: 0
Total persistido no CSV: 60

,model_name,dataset_name,input_type,used_enriched_data,train_samples,test_samples,num_classes,metric_average,accuracy,f1,precision,recall,training_time_sec,epochs,image_height,image_width
0,XGBoost,adult income,tabular,False,39073,9769,2,binary,0.877162,0.716714,0.799789,0.649273,0.222576,NaN,NaN,NaN
1,XGBoost,adult income,tabular,True,59448,9769,2,binary,0.874706,0.708294,0.799785,0.635586,0.194354,NaN,NaN,NaN
2,NCTD Base,adult income,image,False,39073,9769,2,binary,0.849319,0.621399,0.779355,0.516681,418.838451,30.0,24.0,24.0
3,NCTD Base,adult income,image,True,59448,9769,2,binary,0.842666,0.630262,0.720176,0.560308,611.552244,30.0,24.0,24.0
4,NCTD Attention (SE),adult income,image,False,39073,9769,2,binary,0.849524,0.631209,0.763350,0.538067,422.542605,30.0,24.0,24.0

## Consolidação final

Ao final da execução, todos os resultados são reunidos em um único DataFrame e persistidos em CSV para análise posterior em outro notebook.

In [13]:
results_df = load_results_csv(RESULTS_CSV_PATH)

if results_df.empty:
    resumo_final = results_df
else:
    resumo_final = results_df.sort_values(
        ["dataset_name", "input_type", "model_name", "used_enriched_data"]
    ).reset_index(drop=True)

print(f"Resultados persistidos em: {RESULTS_CSV_PATH}")
print(f"Execuções novas nesta sessão: {executed_in_session}")
print(f"Execuções puladas nesta sessão: {skipped_in_session}")

resumo_final

Resultados persistidos em: data/results_models.csv
Execuções novas nesta sessão: 60
Execuções puladas nesta sessão: 0

,model_name,dataset_name,input_type,used_enriched_data,train_samples,test_samples,num_classes,metric_average,accuracy,f1,precision,recall,training_time_sec,epochs,image_height,image_width
0,NCTD Asymmetric Kernels,adult income,image,False,39073,9769,2,binary,0.850957,0.672220,0.709601,0.638580,435.515064,30.0,24.0,24.0
1,NCTD Asymmetric Kernels,adult income,image,True,59448,9769,2,binary,0.813594,0.630104,0.600000,0.663388,679.711279,30.0,24.0,24.0
2,NCTD Attention (SE),adult income,image,False,39073,9769,2,binary,0.849524,0.631209,0.763350,0.538067,422.542605,30.0,24.0,24.0
3,NCTD Attention (SE),adult income,image,True,59448,9769,2,binary,0.851264,0.646558,0.749577,0.568435,654.945175,30.0,24.0,24.0
4,NCTD Base,adult income,image,False,39073,9769,2,binary,0.849319,0.621399,0.779355,0.516681,418.838451,30.0,24.0,24.0
5,NCTD Base,adult income,image,True,59448,9769,2,binary,0.842666,0.630262,0.720176,0.560308,611.552244,30.0,24.0,24.0
6,NCTD Dilated Convolutions,adult income,image,False,39073,9769,2,binary,0.848500,0.632389,0.754147,0.544482,417.589121,30.0,24.0,24.0
7,NCTD Dilated Convolutions,adult income,image,True,59448,9769,2,binary,0.844406,0.646512,0.708461,0.594525,598.417570,30.0,24.0,24.0
8,NCTD Residual,adult income,image,False,39073,9769,2,binary,0.846351,0.637001,0.732888,0.563302,417.563087,30.0,24.0,24.0
9,NCTD Residual,adult income,image,True,59448,9769,2,binary,0.848091,0.646667,0.729323,0.580838,638.513975,30.0,24.0,24.0
10,XGBoost,adult income,tabular,False,39073,9769,2,binary,0.877162,0.716714,0.799789,0.649273,0.222576,NaN,NaN,NaN
11,XGBoost,adult income,tabular,True,59448,9769,2,binary,0.874706,0.708294,0.799785,0.635586,0.194354,NaN,NaN,NaN
12,NCTD Asymmetric Kernels,maintenance,image,False,8000,2000,2,binary,0.981000,0.724638,0.714286,0.735294,13.233648,30.0,12.0,12.0
13,NCTD Asymmetric Kernels,maintenance,image,True,15458,2000,2,binary,0.977000,0.646154,0.677419,0.617647,25.579066,30.0,12.0,12.0
14,NCTD Attention (SE),maintenance,image,False,8000,2000,2,binary,0.977000,0.689189,0.637500,0.750000,15.023401,30.0,12.0,12.0
15,NCTD Attention (SE),maintenance,image,True,15458,2000,2,binary,0.971500,0.636943,0.561798,0.735294,28.849682,30.0,12.0,12.0
16,NCTD Base,maintenance,image,False,8000,2000,2,binary,0.979000,0.704225,0.675676,0.735294,10.845091,30.0,12.0,12.0
17,NCTD Base,maintenance,image,True,15458,2000,2,binary,0.968500,0.608696,0.526882,0.720588,20.779952,30.0,12.0,12.0
18,NCTD Dilated Convolutions,maintenance,image,False,8000,2000,2,binary,0.975500,0.683871,0.609195,0.779412,10.801706,30.0,12.0,12.0
19,NCTD Dilated Convolutions,maintenance,image,True,15458,2000,2,binary,0.967500,0.591195,0.516484,0.691176,20.508535,30.0,12.0,12.0
20,NCTD Residual,maintenance,image,False,8000,2000,2,binary,0.978000,0.710526,0.642857,0.794118,13.011845,30.0,12.0,12.0
21,NCTD Residual,maintenance,image,True,15458,2000,2,binary,0.975500,0.637037,0.641791,0.632353,24.802765,30.0,12.0,12.0
22,XGBoost,maintenance,tabular,False,8000,2000,2,binary,0.988500,0.809917,0.924528,0.720588,0.174770,NaN,NaN,NaN
23,XGBoost,maintenance,tabular,True,15458,2000,2,binary,0.969500,0.601307,0.541176,0.676471,0.180419,NaN,NaN,NaN
24,NCTD Asymmetric Kernels,statlog,image,False,46400,11600,7,macro,0.998190,0.669769,0.713166,0.647059,83.912737,30.0,14.0,14.0
25,NCTD Asymmetric Kernels,statlog,image,True,255283,11600,7,macro,0.997500,0.632089,0.677182,0.619902,459.842501,30.0,14.0,14.0
26,NCTD Attention (SE),statlog,image,False,46400,11600,7,macro,0.998103,0.662210,0.713087,0.632773,87.745115,30.0,14.0,14.0
27,NCTD Attention (SE),statlog,image,True,255283,11600,7,macro,0.997931,0.663783,0.706082,0.636725,482.399921,30.0,14.0,14.0
28,NCTD Base,statlog,image,False,46400,11600,7,macro,0.997931,0.653630,0.712853,0.618269,65.516953,30.0,14.0,14.0
29,NCTD Base,statlog,image,True,255283,11600,7,macro,0.997586,0.618406,0.658154,0.593649,359.987256,30.0,14.0,14.0
30,NCTD Dilated Convolutions,statlog,image,False,46400,11600,7,macro,0.996466,0.596142,0.649638,0.603173,65.418842,30.0,14.0,14.0
31,NCTD Dilated Convolutions,statlog,image,True,255283,11600,7,macro,0.996121,0.596428,0.658201,0.563914,359.706066,30.0,14.0,14.0
32,NCTD Residual,statlog,image,False,46400,11600,7,macro,0.997931,0.653838,0.713066,0.618472,81.405708,30.0,14.0,14.0
33,NCTD Residual,statlog,image,True,255283,11600,7,macro,0.997241,0.601116,0.650475,0.607094,445.438110,30.0,14.0,14.0
34,XGBoost,statlog,tabular,False,46400,11600,7,macro,0.998362,0.681579,0.693109,0.672142,1.077035,NaN,NaN,NaN
35,XGBoost,statlog,tabular,True,255283,11600,7,macro,0.996897,0.526112,0.569201,0.503717,1.780723,NaN,NaN,NaN
36,NCTD Asymmetric Kernels,stroke,image,False,4088,1022,2,binary,0.951076,0.000000,0.000000,0.000000,23.104035,30.0,20.0,20.0
37,NCTD Asymmetric Kernels,stroke,image,True,7778,1022,2,binary,0.906067,0.172414,0.151515,0.200000,43.869807,30.0,20.0,20.0
38,NCTD Attention (SE),stroke,image,False,4088,1022,2,binary,0.951076,0.000000,0.000000,0.000000,22.616838,30.0,20.0,20.0
39,NCTD Attention (SE),stroke,image,True,7778,1022,2,binary,0.832681,0.181818,0.119497,0.380000,42.842557,30.0,20.0,20.0
40,NCTD Base,stroke,image,False,4088,1022,2,binary,0.951076,0.000000,0.000000,0.000000,20.841920,30.0,20.0,20.0
41,NCTD Base,stroke,image,True,7778,1022,2,binary,0.888454,0.185714,0.144444,0.260000,39.226549,30.0,20.0,20.0
42,NCTD Dilated Convolutions,stroke,image,False,4088,1022,2,binary,0.951076,0.000000,0.000000,0.000000,20.650190,30.0,20.0,20.0
43,NCTD Dilated Convolutions,stroke,image,True,7778,1022,2,binary,0.890411,0.176471,0.139535,0.240000,39.258574,30.0,20.0,20.0
44,NCTD Residual,stroke,image,False,4088,1022,2,binary,0.951076,0.000000,0.000000,0.000000,22.568468,30.0,20.0,20.0
45,NCTD Residual,stroke,image,True,7778,1022,2,binary,0.879648,0.185430,0.138614,0.280000,42.880632,30.0,20.0,20.0
46,XGBoost,stroke,tabular,False,4088,1022,2,binary,0.950098,0.072727,0.400000,0.040000,0.173883,NaN,NaN,NaN
47,XGBoost,stroke,tabular,True,7778,1022,2,binary,0.947162,0.068966,0.250000,0.040000,0.171801,NaN,NaN,NaN
48,NCTD Asymmetric Kernels,student,image,False,3539,885,3,macro,0.676836,0.626138,0.631463,0.635146,129.467829,30.0,72.0,72.0
49,NCTD Asymmetric Kernels,student,image,True,5301,885,3,macro,0.737853,0.617101,0.665216,0.615717,193.641874,30.0,72.0,72.0
50,NCTD Attention (SE),student,image,False,3539,885,3,macro,0.715254,0.609284,0.628137,0.606001,116.104767,30.0,72.0,72.0
51,NCTD Attention (SE),student,image,True,5301,885,3,macro,0.468927,0.478809,0.621224,0.544535,174.326492,30.0,72.0,72.0
52,NCTD Base,student,image,False,3539,885,3,macro,0.616949,0.589052,0.605498,0.603227,109.662539,30.0,72.0,72.0
53,NCTD Base,student,image,True,5301,885,3,macro,0.438418,0.443255,0.549880,0.517375,163.316210,30.0,72.0,72.0
54,NCTD Dilated Convolutions,student,image,False,3539,885,3,macro,0.700565,0.530698,0.648389,0.562978,108.093420,30.0,72.0,72.0
55,NCTD Dilated Convolutions,student,image,True,5301,885,3,macro,0.670056,0.631116,0.650228,0.636992,162.130565,30.0,72.0,72.0
56,NCTD Residual,student,image,False,3539,885,3,macro,0.664407,0.506627,0.533344,0.535488,120.319426,30.0,72.0,72.0
57,NCTD Residual,student,image,True,5301,885,3,macro,0.635028,0.546249,0.557822,0.541884,181.308708,30.0,72.0,72.0
58,XGBoost,student,tabular,False,3539,885,3,macro,0.775141,0.711487,0.724600,0.703440,0.549803,NaN,NaN,NaN
59,XGBoost,student,tabular,True,5301,885,3,macro,0.763842,0.690940,0.712338,0.680798,0.545825,NaN,NaN,NaN